// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://welnbkjzqowilggnxuoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlbG5ia2p6cW93aWxnZ254dW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MTU4MTUsImV4cCI6MjA2NDQ5MTgxNX0.HY4PbRohFzEq_S2EnjlLRE52JSJQ4GWd3bTOoErtUiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);